spring:
  application:
    name: security11
  profiles:
    active: self
  resources:
    add-mappings: false
    static-locations: classpath:/static/,classpath:/templates/index/
    #,classpath:/META-INF/resources/webjars/,classpath:/META-INF/resources
  #   static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  #,file:${web.upload-path},file:${web.vue-path}
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #https://blog.csdn.net/zoeou/article/details/78629032
  security:
    user:
      name: root
      password: admin


arc:
  security:
    browser:
      #login的地址是斜线打头的，否则报错
      loginUrl: /authentication/require
      loginProcessingUrl: /v2/login/form/process
      cookieKey: ARC
    code:
      length: 4
      image:
        width: 100
        height: 80
        expiredSecond: 60
        url: /abc
      sms:
        test: aaa

